version: 0.2
env:
  variables:
    APP_NAME: 'training-frontend-angular'
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo install process started
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install 
      - npm install -g @angular/cli
  build:
    commands:
      - echo building...
      - ng build --configuration=production
artifacts:
  files:
  - '**/*'
  discard-paths: no
  base-directory: dist/training-frontend-angular
  